import mongoose from 'mongoose';
import { env } from '../config/env.js';
import { User } from '../models/User.js';
import { Project } from '../models/Project.js';
import { Issue } from '../models/Issue.js';
import { Activity } from '../models/Activity.js';
import { ROLES } from '../constants/roles.js';
import {
  ISSUE_STATUS,
  ISSUE_PRIORITY,
  ISSUE_SEVERITY,
} from '../constants/issueWorkflow.js';
import { generateEmployeeId } from '../services/user.service.js';
import { logger } from './logger.js';

export const getSeedAccounts = () => [
  {
    name: env.ADMIN_NAME || 'Admin User',
    email: env.ADMIN_EMAIL || 'admin@bugboard.test',
    password: env.ADMIN_PASSWORD || 'Password123!',
    role: ROLES.ADMIN,
    employeeId: env.ADMIN_EMPLOYEE_ID || 'ADM-0001',
    department: env.ADMIN_DEPARTMENT || 'Platform Operations',
    designation: env.ADMIN_DEPARTMENT || 'Platform Operations',
  },
  {
    name: 'Lead Developer',
    email: 'dev@bugboard.test',
    password: 'Password123!',
    role: ROLES.DEVELOPER,
    department: 'Engineering',
    designation: 'Principal Engineer',
  },
  {
    name: 'QA Tester',
    email: 'tester@bugboard.test',
    password: 'Password123!',
    role: ROLES.TESTER,
    department: 'Quality Assurance',
    designation: 'Senior QA Specialist',
  },
];

export const SEED_ACCOUNTS = getSeedAccounts();

export const seedSampleData = async () => {
  const accounts = getSeedAccounts();
  const users = {};
  for (const account of accounts) {
    let user;
    if (account.role === ROLES.ADMIN) {
      user = (await User.findOne({ email: account.email })) || (await User.findOne({ role: ROLES.ADMIN }));
    } else {
      user = await User.findOne({ email: account.email });
    }

    if (!user) {
      // Admin employeeId is configured from .env, NOT generated by counter
      const employeeId =
        account.role === ROLES.ADMIN ? account.employeeId : await generateEmployeeId(account.role);

      user = new User({
        name: account.name,
        email: account.email,
        passwordHash: account.password,
        role: account.role,
        employeeId,
        department: account.department,
        designation: account.designation || account.department,
      });
      await user.save();
      console.log(`✅ Created user: ${account.name} (${account.role}) with ID ${employeeId}`);
    } else {
      // Idempotent upsert of identity & department on existing seeded records
      let needsSave = false;
      if (account.role === ROLES.ADMIN) {
        if (user.email !== account.email) {
          user.email = account.email;
          needsSave = true;
        }
        if (user.employeeId !== account.employeeId) {
          user.employeeId = account.employeeId;
          needsSave = true;
        }
        if (user.department !== account.department) {
          user.department = account.department;
          user.designation = account.department;
          needsSave = true;
        }
      } else {
        if (!user.employeeId) {
          user.employeeId = await generateEmployeeId(account.role);
          needsSave = true;
        }
        if (account.department && user.department !== account.department) {
          user.department = account.department;
          user.designation = account.department;
          needsSave = true;
        }
      }

      if (needsSave) {
        await user.save();
        console.log(`🔄 Updated seed user: ${user.name} (${user.role}) with Department: ${user.department}, ID: ${user.employeeId}`);
      }
    }
    users[account.role] = user;
  }

  // Seed Projects
  let proj1 = await Project.findOne({ key: 'CORE' });
  if (!proj1) {
    proj1 = await Project.create({
      name: 'Core Platform Engine',
      key: 'CORE',
      description: 'Distributed event pipeline, auth subsystem, and persistence engine.',
      members: [users[ROLES.ADMIN]._id, users[ROLES.DEVELOPER]._id, users[ROLES.TESTER]._id],
    });
    console.log('✅ Created project: Core Platform Engine (CORE)');
  }

  let proj2 = await Project.findOne({ key: 'UI' });
  if (!proj2) {
    proj2 = await Project.create({
      name: 'Web Interface Console',
      key: 'UI',
      description: 'React SPA engineering console, responsive layouts, and data grids.',
      members: [users[ROLES.ADMIN]._id, users[ROLES.DEVELOPER]._id, users[ROLES.TESTER]._id],
    });
    console.log('✅ Created project: Web Interface Console (UI)');
  }

  // Seed sample issues
  const existingIssuesCount = await Issue.countDocuments();
  if (existingIssuesCount === 0) {
    const sampleIssues = [
      {
        title: 'Memory leak under sustained high socket traffic',
        description: 'Buffer retention in TCP connection handler causes 2MB/min heap growth under load.',
        project: proj1._id,
        severity: ISSUE_SEVERITY.CRITICAL,
        priority: ISSUE_PRIORITY.URGENT,
        status: ISSUE_STATUS.OPEN,
        reporter: users[ROLES.TESTER]._id,
        assignee: users[ROLES.DEVELOPER]._id,
      },
      {
        title: 'JWT access token validation fails on clock skew > 500ms',
        description: 'Need to configure 5s clock tolerance leeway in verification options.',
        project: proj1._id,
        severity: ISSUE_SEVERITY.HIGH,
        priority: ISSUE_PRIORITY.HIGH,
        status: ISSUE_STATUS.IN_PROGRESS,
        reporter: users[ROLES.DEVELOPER]._id,
        assignee: users[ROLES.DEVELOPER]._id,
      },
      {
        title: 'Database connection retry backoff missing jitter',
        description: 'Thundering herd on replica set failover causes ephemeral connection storm.',
        project: proj1._id,
        severity: ISSUE_SEVERITY.MEDIUM,
        priority: ISSUE_PRIORITY.MEDIUM,
        status: ISSUE_STATUS.TESTING,
        reporter: users[ROLES.DEVELOPER]._id,
        assignee: users[ROLES.DEVELOPER]._id,
      },
      {
        title: 'Keyboard focus ring clipped on high DPI displays',
        description: 'Outline offset clips against overflow-hidden card containers at 150% scaling.',
        project: proj2._id,
        severity: ISSUE_SEVERITY.LOW,
        priority: ISSUE_PRIORITY.LOW,
        status: ISSUE_STATUS.RESOLVED,
        reporter: users[ROLES.TESTER]._id,
        assignee: users[ROLES.DEVELOPER]._id,
      },
      {
        title: 'Mobile filter bottom-sheet scroll chaining bug',
        description: 'Scrolling inside bottom sheet activates background window scroll on iOS Safari.',
        project: proj2._id,
        severity: ISSUE_SEVERITY.HIGH,
        priority: ISSUE_PRIORITY.HIGH,
        status: ISSUE_STATUS.OPEN,
        reporter: users[ROLES.TESTER]._id,
        assignee: null,
      },
    ];

    for (const issueData of sampleIssues) {
      const issue = await Issue.create(issueData);
      await Activity.create({
        issue: issue._id,
        actor: users[ROLES.ADMIN]._id,
        action: 'CREATED',
        field: 'issue',
        oldValue: null,
        newValue: issue.title,
        createdAt: new Date(),
      });
      console.log(`✅ Created issue: ${issue.title} [${issue.status}]`);
    }
  }
};

export const seedDatabase = async () => {
  try {
    logger.info({ uri: env.MONGODB_URI }, 'Connecting to MongoDB for seeding...');
    await mongoose.connect(env.MONGODB_URI, {
      serverSelectionTimeoutMS: 5000,
    });
    logger.info('Connected to MongoDB.');

    console.log('\n=============================================================');
    console.log('🌱 BugBoard Database Seeder — Projects, Issues, and Users');
    console.log('=============================================================\n');

    await seedSampleData();

    console.log('\n-------------------------------------------------------------');
    console.log('🔑 SAMPLE CREDENTIALS FOR REVIEWERS:');
    console.log('-------------------------------------------------------------');
    console.table(
      SEED_ACCOUNTS.map((acc) => ({
        Role: acc.role,
        Email: acc.email,
        Password: acc.password,
        Department: acc.department,
      }))
    );
    console.log('=============================================================\n');

    await mongoose.connection.close();
    logger.info('Database connection closed. Seeding complete.');
  } catch (error) {
    logger.fatal({ err: error.message }, 'Seeding failed');
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

// Execute if run directly from CLI
if (process.argv[1] && process.argv[1].endsWith('seed.js')) {
  seedDatabase();
}
